package com.atguigu.mbg.mapper;

import com.atguigu.mbg.entities.Paid;
import java.util.List;

public interface PaidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Sat Apr 21 14:35:46 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Sat Apr 21 14:35:46 CST 2018
     */
    int insert(Paid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Sat Apr 21 14:35:46 CST 2018
     */
    Paid selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Sat Apr 21 14:35:46 CST 2018
     */
    List<Paid> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table case_paid
     *
     * @mbggenerated Sat Apr 21 14:35:46 CST 2018
     */
    int updateByPrimaryKey(Paid record);
}